document.addEventListener("DOMContentLoaded", function () {
  (function ($) {
    $(document).ready(function () {
      $("#custom-dropdown").on("change", function () {
        const language = $(this).val();
        const postId = $("#post_id").text();
        $("#translating_result").show().text("Translating ...");
        console.log(language);
        const Keywords = {
          en: [
            "Description",
            "Tasting Notes",
            "Type",
            "Wine Sub Type",
            "Sparking Type",
            "Vinification",
            "Year",
            "Grapes",
            "Country",
            "Color",
            "Alcohol",
            "Region",
            "Serving Temperature",
            "Aging",
            "Soil Type",
            "Dosage",
            "Classification",
            "Winemaker",
            "Total Acidity",
            "pH",
            "Sugar",
            "So2",
            "Keep",
            "Vineyard Type",
            "Vineyard Climate",
            "Vineyard Yield",
            "Vineyard Area",
            "Vineyard Age",
            "Emotions",
            "Emotions2",
            "Emotions3",
            "Region",
            "France",
            "Italy",
            "New",
            "Swi",
            "Other",
            "Ingredients",
            "Harvest",
            "Containers(s)",
            "BottleTextZero",
          ],
          es: [
            "Descripción",
            "Notas de cata",
            "Tipo",
            "Subtipo de vino",
            "Tipo de vino espumoso",
            "Vinificación",
            "Año",
            "Uvas",
            "País",
            "Color",
            "Alcohol",
            "Región",
            "Temperatura de servicio",
            "Envejecimiento",
            "Tipo de suelo",
            "Dosis",
            "Clasificación",
            "Enólogo",
            "Acidez total",
            "pH",
            "Azúcar",
            "So2",
            "Conservación",
            "Tipo de viñedo",
            "Clima del viñedo",
            "Rendimiento del viñedo",
            "Área del viñedo",
            "Edad del viñedo",
            "Emociones",
            "Emociones2",
            "Emociones3",
            "Región",
            "Francia",
            "Italia",
            "Nuevo",
            "Swi",
            "Otro",
            "Ingredientes",
            "Cosecha",
            "Contenedor(es)",
            "BottleTextZero",
          ],
          fr: [
            "Description",
            "Notes de dégustation",
            "Taper",
            "Sous-type de vin",
            "Taper de vin mousseux",
            "Vinification",
            "Année",
            "Cépages",
            "Pays",
            "Couleur",
            "Alcool",
            "Région",
            "Température de service",
            "Vieillissement",
            "Type de sol",
            "Dosage",
            "Classification",
            "Vigneron",
            "Acidité totale",
            "pH",
            "Sucre",
            "So2",
            "Garde",
            "Type de vignoble",
            "Climat du vignoble",
            "Rendement du vignoble",
            "Superficie du vignoble",
            "Âge du vignoble",
            "Émotions",
            "Émotions2",
            "Emotions3",
            "Région",
            "France",
            "Italie",
            "Nouveau",
            "Suisse",
            "Autre",
            "Ingrédients",
            "Récolte",
            "Contenant(s)",
            "BottleTextZero",
          ],
          pt: [
            "Descrição",
            "Notas de prova",
            "Tipo",
            "Subtipo de vinho",
            "Tipo de faísca",
            "Vinificação",
            "Ano",
            "Uvas",
            "País",
            "Cor",
            "Álcool",
            "Região",
            "Temperatura de Serviço",
            "Envelhecimento",
            "Tipo de solo",
            "Dosagem",
            "Classificação",
            "Enólogo",
            "Acidez Total",
            "pH",
            "Açúcar",
            "So2",
            "Manter",
            "Tipo Vinha",
            "Clima da Vinha",
            "Rendimento da Vinha",
            "Área de Vinha",
            "Idade da Vinha",
            "Emoções",
            "Emoções2",
            "Emoções3",
            "Região",
            "França",
            "Itália",
            "Novo",
            "Swi",
            "Outro",
            "Ingredientes",
            "Colheita",
            "Contentores(es)",
            "BottleTextZero",
          ],
          it: [
            "Descrizione",
            "Note di degustazione",
            "Tipo",
            "Sottotipo di vino",
            "Tipo di spumante",
            "Vinificazione",
            "Anno",
            "Uve",
            "Paese",
            "Colore",
            "Alcol",
            "Regione",
            "Temperatura di servizio",
            "Invecchiamento",
            "Tipo di terreno",
            "Dosaggio",
            "Classificazione",
            "Enologo",
            "Acidità totale",
            "pH",
            "Zucchero",
            "So2",
            "Conservazione",
            "Tipo di vigneto",
            "Clima del vigneto",
            "Resa del vigneto",
            "Superficie del vigneto",
            "Età del vigneto",
            "Emozioni",
            "Emozioni2",
            "Emotions3",
            "Regione",
            "Francia",
            "Italia",
            "Nuovo",
            "Swi",
            "Altro",
            "Ingredienti",
            "Raccolto",
            "Contenitore(i)",
            "BottleTextZero",
          ],
          de: [
            "Beschreibung",
            "Verkostungsnotizen",
            "Typ",
            "Weinuntertyp",
            "Schaumweintyp",
            "Weinbereitung",
            "Jahr",
            "Trauben",
            "Land",
            "Farbe",
            "Alkohol",
            "Region",
            "Serviertemperatur",
            "Reifung",
            "Bodenart",
            "Dosierung",
            "Klassifizierung",
            "Winzer",
            "Gesamtsäure",
            "pH",
            "Zucker",
            "SO2",
            "Haltbarkeit",
            "Weinbergstyp",
            "Weinbergsklima",
            "Weinbergsertrag",
            "Weinbergsfläche",
            "Weinbergsalter",
            "Emotionen",
            "Emotionen2",
            "Emotionen3",
            "Region",
            "Frankreich",
            "Italien",
            "Neu",
            "Schweiz",
            "Andere",
            "Zutaten",
            "Ernte",
            "Behälter",
            "BottleTextZero",
          ],
          nl: [
            "Beschrijving",
            "Proefnotities",
            "Type",
            "Subtype wijn",
            "Sparkingtype",
            "Vinificatie",
            "Jaar",
            "Druiven",
            "Land",
            "Kleur",
            "Alcohol",
            "Regio",
            "Serveertemperatuur",
            "Rijging",
            "Bodemtype",
            "Dosering",
            "Classificatie",
            "Wijnmaker",
            "Totale zuurgraad",
            "pH",
            "Suiker",
            "So2",
            "Bewaren",
            "Type wijngaard",
            "Klimaat wijngaard",
            "Opbrengst wijngaard",
            "Wijngaardgebied",
            "Wijngaardleeftijd",
            "Emoties",
            "Emoties2",
            "Emoties3",
            "Regio",
            "Frankrijk",
            "Italië",
            "Nieuw",
            "Zwitserland",
            "Anders",
            "Ingrediënten",
            "Oogst",
            "Containers(s)",
            "BottleTextZero",
          ],
          pl: [
            "Opis",
            "Notatki degustacyjne",
            "Typ",
            "Podtyp wina",
            "Typ musujacego wina",
            "Winifikacja",
            "Rok",
            "Winogrona",
            "Kraj",
            "Kolor",
            "Alkohol",
            "Region",
            "Temperatura serwowania",
            "Starzenie",
            "Typ gleby",
            "Dawka",
            "Klasyfikacja",
            "Winiarz",
            "Calkowita kwasowosc",
            "pH",
            "Cukier",
            "So2",
            "Przechowywanie",
            "Typ winnicy",
            "Klimat winnicy",
            "Plon winnicy",
            "Obszar winnicy",
            "Wiek winnicy",
            "Emocje",
            "Emocje2",
            "Emocje3",
            "Region",
            "Francja",
            "Wlochy",
            "Nowy",
            "Szwajcarski",
            "Inne",
            "Skladniki",
            "Zbiory",
            "Pojemniki(i)",
            "BottleTextZero",
          ],
          ro: [
            "Descriere",
            "Note de degustare",
            "Tip",
            "Sub tip vin",
            "Tipul de scânteie",
            "Vinificare",
            "Anul",
            "Struguri",
            "?ara",
            "Culoare",
            "Alcool",
            "Regiune",
            "Temperatura de servire",
            "Îmbatrânire",
            "Tipul de sol",
            "Dozaj",
            "Clasificare",
            "Vinicul",
            "Aciditate totala",
            "pH",
            "Zahar",
            "So2",
            "Pastra?i",
            "Tipul podgorie",
            "Clima podgoriilor",
            "Veyard Yield",
            "Zona podgorica",
            "Veyard Age",
            "Emo?ii",
            "Emo?ii2",
            "Emo?ii3",
            "Regiune",
            "Fran?a",
            "Italia",
            "Nou",
            "Swi",
            "Altele",
            "Ingrediente",
            "Recolta",
            "Containere(e)",
            "BottleTextZero",
          ],
          dk: [
            "Beskrivelse",
            "Smagsnoter",
            "Skriv",
            "Vinundertype",
            "Gnisttype",
            "Vinifikation",
            "År",
            "Druer",
            "Land",
            "Farve",
            "Alkohol",
            "Region",
            "Serveringstemperatur",
            "Aldring",
            "Jordtype",
            "Dosis",
            "Klassificering",
            "Vinmager",
            "Total syreindhold",
            "pH",
            "Sukker",
            "So2",
            "Behold",
            "Vinyard Type",
            "Vingårdsklima",
            "Vinyard Yield",
            "Vinmarksområde",
            "Vineyard Age",
            "Følelser",
            "Følelser2",
            "Følelser3",
            "Region",
            "Frankrig",
            "Italien",
            "Ny",
            "Swi",
            "Andet",
            "Ingredienser",
            "Høst",
            "Beholdere",
            "BottleTextZero",
          ],
          no: [
            "Beskrivelse",
            "Smaksnotater",
            "Skriv",
            "Vin Sub Type",
            "Gnisttype",
            "Vinifisering",
            "År",
            "Druer",
            "Land",
            "Farge",
            "Alkohol",
            "Region",
            "Serveringstemperatur",
            "Aldring",
            "Jordtype",
            "Dosering",
            "Klassifisering",
            "Vinmaker",
            "Total surhet",
            "pH",
            "Sukker",
            "So2",
            "Behold",
            "Vingårdstype",
            "Vingårdsklima",
            "Vinyard Yield",
            "Vingårdsområde",
            "Vingårdsalderen",
            "Følelser",
            "Følelser2",
            "Følelser3",
            "Region",
            "Frankrike",
            "Italia",
            "Ny",
            "Swi",
            "Annet",
            "Ingredienser",
            "Høst",
            "Beholder(e)",
            "BottleTextZero",
          ],
          uk: [
            "Опис",
            "Дегустаційні нотки",
            "Тип",
            "Тип вина",
            "Тип ігристого",
            "Виноробство",
            "Рік",
            "Сорти винограду",
            "Країна",
            "Колір",
            "Алкоголь",
            "Регіон",
            "Температура подачі",
            "Витримка",
            "Тип ґрунту",
            "Доза",
            "Класифікація",
            "Винороб",
            "Загальна кислотність",
            "рН",
            "Цукор",
            "SO2",
            "Зберігання",
            "Тип виноградника",
            "Клімат виноградника",
            "Урожайність виноградника",
            "Площа виноградника",
            "Вік виноградника",
            "Емоції",
            "Емоції2",
            "Емоції3",
            "Регіон",
            "Франція",
            "Італія",
            "Новинка",
            "Швейцарія",
            "Інші",
            "Інгредієнти",
            "Урожай",
            "Контейнери",
            "Текст на пляшці",
          ],
          ru: [
            "Описание",
            "Дегустационные заметки",
            "Тип",
            "Подтип вина",
            "Тип игристого",
            "Винификация",
            "Год",
            "Сорта винограда",
            "Страна",
            "Цвет",
            "Алкоголь",
            "Регион",
            "Температура подачи",
            "Выдержка",
            "Тип почвы",
            "Доза",
            "Классификация",
            "Винодел",
            "Общая кислотность",
            "pH",
            "Сахар",
            "SO2",
            "Хранение",
            "Тип виноградника",
            "Климат виноградника",
            "Урожайность виноградника",
            "Площадь виноградника",
            "Возраст виноградника",
            "Эмоции",
            "Эмоции2",
            "Эмоции3",
            "Регион",
            "Франция",
            "Италия",
            "Новинка",
            "Швейцария",
            "Другое",
            "Ингредиенты",
            "Урожай",
            "Контейнеры",
            "Текст на бутылке",
          ],
        };
        if (language) {
          $.ajax({
            url: ajax_object.ajax_url,
            type: "POST",
            data: {
              action: "translate_text",
              language: language,
              postId: postId,
            },
            beforeSend: function () {
              $("#translating_result").text("Translating ...");
            },
            success: function (response) {
              try {
                const rawData = JSON.parse(response);
                console.log("testest");
                const dataTitle = Keywords[language];
                console.log(rawData);
                console.log("Title Data");
                console.log(dataTitle);
                const { data } = rawData;
                $("#tasting_notes .elementor-heading-title").text(dataTitle[1]);
                $("#type .elementor-heading-title").text(dataTitle[2]);
                $("#vinification .elementor-heading-title").text(dataTitle[5]);
                $("#year .elementor-heading-title").text(dataTitle[6]);
                $("#grapes .elementor-heading-title").text(dataTitle[7]);
                $("#country .elementor-heading-title").text(dataTitle[8]);
                $("#color .elementor-heading-title").text(dataTitle[9]);
                $("#alcohol .elementor-heading-title").text(dataTitle[10]);
                $("#region .elementor-heading-title").text(dataTitle[11]);
                $("#serving_temperature .elementor-heading-title").text(
                  dataTitle[12]
                );
                $("#aging .elementor-heading-title").text(dataTitle[13]);
                $("#soil_type .elementor-heading-title").text(dataTitle[14]);
                $("#dosage .elementor-heading-title").text(dataTitle[15]);
                $("#classification .elementor-heading-title").text(
                  dataTitle[16]
                );
                $("#winemaker .elementor-heading-title").text(dataTitle[17]);
                $("#total_acidity .elementor-heading-title").text(
                  dataTitle[18]
                );
                $("#ph .elementor-heading-title").text(dataTitle[19]);
                $("#sugar .elementor-heading-title").text(dataTitle[20]);
                $("#sotwo .elementor-heading-title").text(dataTitle[21]);
                $("#keep .elementor-heading-title").text(dataTitle[22]);

                $("#vineyard_type .elementor-heading-title").text(
                  dataTitle[23]
                );
                $("#vineyard_climate .elementor-heading-title").text(
                  dataTitle[24]
                );
                $("#vineyard_yield .elementor-heading-title").text(
                  dataTitle[25]
                );
                $("#vineyard_area .elementor-heading-title").text(
                  dataTitle[26]
                );
                $("#vineyard_age .elementor-heading-title").text(dataTitle[27]);

                $("#emotions .elementor-heading-title").text(dataTitle[28]);
                $("#ingredients .elementor-heading-title").text(dataTitle[37]);
                $("#harvest .elementor-heading-title").text(dataTitle[38]);
                $("#containers .elementor-heading-title").text(dataTitle[39]);
                if (Array.isArray(data) || 1) {
                  updateFields(data);

                  $("#translating_result").hide();
                } else {
                  console.error("Unexpected response format:", response);
                  $("#translating_result").text("Translation failed.");
                }
              } catch (error) {
                console.error("Error parsing response:", error);
                $("#translating_result").text("Translation failed.");
              }
            },
            error: function (jqXHR, textStatus, errorThrown) {
              console.error("AJAX error:", textStatus, errorThrown);
              $("#translating_result").text(
                "An error occurred during translation."
              );
            },
          });
        } else {
          $("#translating_result").hide();
        }
      });

      function updateFields(data) {
        const fieldMapping = [
          {
            id: "#wine_name .jet-listing-dynamic-field__content",
            contentIndex: 0,
          },
          {
            id: "#wine_description .jet-listing-dynamic-field__content",
            contentIndex: 1,
          },
          {
            id: "#tasting_notes_value .jet-listing-dynamic-field__content",
            contentIndex: 2,
            key: "content",
          },
          {
            id: "#type_product .jet-listing-dynamic-field__content",
            contentIndex: 3,
            key: "content",
          },
          {
            id: "#type_white .jet-listing-dynamic-field__content",
            contentIndex: 4,
          },
          {
            id: "#type_sparking .jet-listing-dynamic-field__content",
            contentIndex: 5,
          },
          {
            id: "#type_fortified .jet-listing-dynamic-field__content",
            contentIndex: 6,
          },
          {
            id: "#vinification_value .jet-listing-dynamic-field__content",
            contentIndex: 7,
            key: "content",
          },
          {
            id: "#year_value .elementor-heading-title",
            contentIndex: 8,
            key: "content",
          },
          {
            id: "#grapes_value .jet-listing-dynamic-field__content",
            contentIndex: 9,
            key: "content",
          },
          {
            id: "#country_value .jet-listing-dynamic-field__content",
            contentIndex: 10,
            key: "content",
          },
          {
            id: "#color_value .jet-listing-dynamic-field__content",
            contentIndex: 11,
            key: "content",
          },
          {
            id: "#alcohol_value .jet-listing-dynamic-field__content",
            contentIndex: 12,
            key: "content",
          },
          {
            id: "#serving_temperature_value .jet-listing-dynamic-field__content",
            contentIndex: 14,
            key: "content",
          },
          {
            id: "#aging_value .jet-listing-dynamic-field__content",
            contentIndex: 15,
            key: "content",
          },
          {
            id: "#soli_type_value .jet-listing-dynamic-field__content",
            contentIndex: 16,
            key: "content",
          },
          {
            id: "#dosage_value .jet-listing-dynamic-field__content",
            contentIndex: 17,
            key: "content",
          },
          {
            id: "#classification_value .jet-listing-dynamic-field__content",
            contentIndex: 18,
            key: "content",
          },
          {
            id: "#winemaker_value .jet-listing-dynamic-field__content",
            contentIndex: 19,
            key: "content",
          },
          {
            id: "#keep_value .jet-listing-dynamic-field__content",
            contentIndex: 24,
            key: "content",
          },
          {
            id: "#vineyard_type_value .jet-listing-dynamic-field__content",
            contentIndex: 25,
            key: "content",
          },
          {
            id: "#vineyard_climate_value .jet-listing-dynamic-field__content",
            contentIndex: 26,
            key: "content",
          },
          {
            id: "#vineyard_yield_value .jet-listing-dynamic-field__content",
            contentIndex: 27,
            key: "content",
          },
          {
            id: "#vineyard_area_value .jet-listing-dynamic-field__content",
            contentIndex: 28,
            key: "content",
          },
          {
            id: "#vineyard_age_value .jet-listing-dynamic-field__content",
            contentIndex: 29,
            key: "content",
          },
          {
            id: "#emotion_one .jet-listing-dynamic-field__content",
            contentIndex: 30,
            key: "content",
          },
          {
            id: "#emotion_two .jet-listing-dynamic-field__content",
            contentIndex: 31,
            key: "content",
          },
          {
            id: "#emotion_three .jet-listing-dynamic-field__content",
            contentIndex: 32,
            key: "content",
          },
          {
            id: "#region_por .jet-listing-dynamic-field__content",
            contentIndex: 33,
            key: "content",
          },
          {
            id: "#region_fr .jet-listing-dynamic-field__content",
            contentIndex: 34,
            key: "content",
          },
          {
            id: "#region_ita .jet-listing-dynamic-field__content",
            contentIndex: 35,
            key: "content",
          },
          {
            id: "#region_ne .jet-listing-dynamic-field__content",
            contentIndex: 36,
            key: "content",
          },
          {
            id: "#region_sw .jet-listing-dynamic-field__content",
            contentIndex: 37,
            key: "content",
          },
          {
            id: "#region_others .jet-listing-dynamic-field__content",
            contentIndex: 38,
            key: "content",
          },
          {
            id: "#ingredients_value .jet-listing-dynamic-field__content",
            contentIndex: 39,
            key: "content",
          },
          {
            id: "#harvest_value .jet-listing-dynamic-field__content",
            contentIndex: 40,
            key: "content",
          },
        ];

        fieldMapping.forEach(({ id, contentIndex, key = "content" }) => {
          const fieldData = data[contentIndex];
          console.log("test");
          if (fieldData) {
            $(id).text(fieldData[key] || "");
          }
        });
        const responseData = data[41].content;
        const translatedItems = responseData
          .split(" | ")
          .filter((item) => item.trim() !== "");
        const repeaterItems = document.querySelectorAll(
          ".jet-listing-dynamic-repeater__item span"
        );
        repeaterItems.forEach((item, index) => {
          if (translatedItems[index]) {
            item.textContent = translatedItems[index];
          }
        });
      }
    });
  })(window.jQuery);
});
